[package]
name = "spu-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Aucune dépendance pour l'instant !
# On utilise notre propre ObjectId
