[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

# Ou utiliser le sparse protocol (plus rapide)
# [source.crates-io]
# replace-with = 'sparse'
# 
# [source.sparse]
# registry = "sparse+https://index.crates.io/"